pairs:
  - sample: AHC_2023_ISB_01
    r1: data-private/AHC_2023_ISB_01_R1.fastq.gz
    r2: data-private/AHC_2023_ISB_01_R2.fastq.gz

discovery:
  min_len_contig: 300
  blast_remote: true

reference:
  fallback_acc: D90457.1

context_accessions:
  - D90457.1
  - AB365074.1
  - AB365075.1
  - AB365076.1
  - AB365077.1
  - AB365078.1

phylogeny:
  wg_model: GTR+G+I
  vp1_model: K2P+I
  bootstrap: 1000
  use_model_finder: false
  min_depth_consensus: 10

kraken2:
  enable: true
  db: /data/db/kraken2/k2_standard_202507

kaiju:
  enable: true
  db_fmi: /data/db/kaiju/kaiju_db_nr_euk.fmi
  nodes: /data/db/kaiju/nodes.dmp
  names: /data/db/kaiju/names.dmp
